spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peekport?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.springframework.security: DEBUG
      com.peekport: DEBUG
      org.springframework.web: DEBUG
